version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # Example: NEXT_PUBLIC_API_URL=http://localhost:8000/api
    volumes:
      # Mount src and public for hot-reloading during development
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      # If you have .env.local for environment variables:
      # - ./frontend/.env.local:/app/.env.local
    # The command for development to enable hot-reloading
    # The Dockerfile's CMD ["npm", "start"] is for production builds/runs.
    command: npm run dev

# If you add other services like a backend, you might define a network:
# networks:
#   app_network:
#     driver: bridge 