version: '3.8'

services:
  db:
    image: postgres:16
    shm_size: 1g
    restart: unless-stopped
    volumes:
      - /home/ubuntu/docker/windmill/db_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5433:5432  # Accesso pubblico per debugging o necessità dirette
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: windmill
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  windmill_server:
    image: ${WM_IMAGE}
    pull_policy: always
    restart: unless-stopped
    expose:
      - 8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MODE=server
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /home/ubuntu/docker/windmill/worker_logs:/tmp/windmill/logs

  windmill_worker:
    image: ${WM_IMAGE}
    pull_policy: always
    deploy:
      replicas: 3
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MODE=worker
      - WORKER_GROUP=default
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/docker/windmill/worker_dependency_cache:/tmp/windmill/cache
      - /home/ubuntu/docker/windmill/worker_logs:/tmp/windmill/logs

  windmill_worker_native:
    image: ${WM_IMAGE}
    pull_policy: always
    deploy:
      replicas: 1
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MODE=worker
      - WORKER_GROUP=native
      - NUM_WORKERS=8
      - SLEEP_QUEUE=200
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /home/ubuntu/docker/windmill/worker_logs:/tmp/windmill/logs

  windmill_worker_reports:
    image: ${WM_IMAGE}
    pull_policy: always
    deploy:
      replicas: 1
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MODE=worker
      - WORKER_GROUP=reports
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/docker/windmill/worker_dependency_cache:/tmp/windmill/cache
      - /home/ubuntu/docker/windmill/worker_logs:/tmp/windmill/logs

  caddy:
    image: ghcr.io/windmill-labs/caddy-l4:latest
    restart: unless-stopped
    ports:
      - 8080:8080  # Porta esposta per il reverse proxy
      - 25:25      # Porta SMTP se necessaria
    volumes:
      - /home/ubuntu/docker/windmill/Caddyfile:/etc/caddy/Caddyfile
      # - ./certs:/certs # Per HTTPS con certificati personalizzati


volumes:
  db_data: null
  worker_dependency_cache: null
  worker_logs: null
  lsp_cache: null
