services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    ports:
      - "9090:9090"
    volumes:
      - /home/ubuntu/docker/monitor/prometheus:/etc/prometheus
      - /home/ubuntu/docker/monitor/prometheus/prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: root
    ports:
      - "3000:3000"
    volumes:
      - /home/ubuntu/docker/monitor/grafana/grafana-data:/var/lib/grafana
    restart: unless-stopped


  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    user: root
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  cadvisor:
    image: google/cadvisor:latest
    user: root
    container_name: cadvisor

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /cgroup:/cgroup:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped



volumes:
  prometheus-data:
  grafana-data:
