version: '3.8'

services:
  frontend:
    image: salvini/forvard-frontend:latest
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    container_name: forvard-frontend
    restart: unless-stopped
    
    # Variabili d'ambiente (se necessarie)
    environment:
      - NODE_ENV=production
    
    # Per i log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Configurazioni di sicurezza
    security_opt:
      - no-new-privileges:true
    
    # Limiti di risorse
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
