version: '3.8'

services:
  # Servizio principale
  frontend:
    image: salvini/forvard-frontend:latest
    container_name: forvard-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount dei certificati Let's Encrypt
      - ./ssl-certs:/etc/ssl/letsencrypt:ro
      - ./nginx-letsencrypt.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - certbot
    networks:
      - frontend-network

  # Servizio per ottenere/rinnovare certificati Let's Encrypt
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./ssl-certs:/etc/letsencrypt
      - ./www-certbot:/var/www/certbot
    command: >
      certonly --webroot --webroot-path=/var/www/certbot
      --email your-email@unime.it
      --agree-tos --no-eff-email
      -d volare.unime.it
    networks:
      - frontend-network

  # Servizio per il rinnovo automatico (opzionale)
  certbot-renew:
    image: certbot/certbot:latest
    container_name: certbot-renew
    volumes:
      - ./ssl-certs:/etc/letsencrypt
      - ./www-certbot:/var/www/certbot
    command: renew --quiet
    profiles:
      - renewal  # Solo per rinnovo manuale
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge

volumes:
  ssl-certs:
  www-certbot:




