name: Frontend Auto Deploy

on:
  push:
    paths:
      - 'frontend_2/**'
    branches:
      - main
      - master
  pull_request:
    paths:
      - 'frontend_2/**'
    branches:
      - main
      - master

env:
  DOCKERHUB_USERNAME: salvini
  IMAGE_NAME: forvard-frontend
  REGISTRY: docker.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value={{date 'YYYYMMDD-HHmmss'}}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend_2
        file: ./frontend_2/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Image digest
      run: echo ${{ steps.build.outputs.digest }}
      
    - name: Update deployment status
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        echo "✅ Frontend deployed successfully!"
        echo "🚀 Image: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest"
        echo "📋 Available tags:"
        echo "${{ steps.meta.outputs.tags }}"
