name: Frontend CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build frontend image for validation
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./frontend/Dockerfile
          platforms: linux/amd64
          push: false # Do not push on PR builds
          load: true # Load image into docker for testing if needed
          tags: salvini/forvard-frontend:test-build
          cache-from: type=gha
          cache-to: type=gha,mode=max 